package me.alexnaupay.platziarchitecture.view

import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import androidx.databinding.DataBindingUtil
import androidx.lifecycle.Observer
import androidx.lifecycle.ViewModelProvider
import me.alexnaupay.platziarchitecture.R
import me.alexnaupay.platziarchitecture.databinding.ActivityMainBinding
import me.alexnaupay.platziarchitecture.entities.Coupon
import me.alexnaupay.platziarchitecture.viewmodel.CouponsViewModel

class MainActivity : AppCompatActivity() {

    private lateinit var couponsViewModel: CouponsViewModel

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        supportActionBar?.hide()

        // VIEW: setup bindings
        setupBindings()
    }

    private fun setupBindings() {
        // 1. xml
        // ActivityMainBinding is autogenerated from activity_main.xml
        val activityMainBinding: ActivityMainBinding =
            DataBindingUtil.setContentView(this, R.layout.activity_main)

        // 2. Its ViewModel
        //couponViewModel = ViewModelProviders.of(this).get(CouponsViewModel::class.java)
        // Get ViewModel instance
        couponsViewModel = ViewModelProvider(this)[CouponsViewModel::class.java]

        activityMainBinding.model = couponsViewModel
        setupListUpdate()
    }

    private fun setupListUpdate() {
        //CallCoupons
        couponsViewModel.callCoupons()

        //getCoupons - Lista de cupones
        couponsViewModel.getCoupons()
            .observe(this, Observer { coupons: List<Coupon> ->
                Log.w("COUPON", coupons[0].title)
                couponsViewModel.setCouponsInRecyclerAdapter(coupons)
            })

        setupCouponCardClick()
    }

    private fun setupCouponCardClick() {
        couponsViewModel.getSelectedCoupon()
            .observe(this, Observer { coupon: Coupon ->
                Log.i("CLICK", coupon.title)

                val detailActivityIntent = Intent(this, CouponDetailActivity::class.java)
                detailActivityIntent.putExtra("COUPON", coupon)
                this.startActivity(detailActivityIntent)
            })
    }
}
